name: Build and Release Installer

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_hachimi_edge:
    name: Build Hachimi-Edge DLL
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: kairusds/Hachimi-Edge
          path: Hachimi-Edge
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: ./Hachimi-Edge
      - uses: dtolnay/rust-toolchain@stable
      - name: Build Hachimi-Edge DLL
        run: cargo build --release
        working-directory: ./Hachimi-Edge
      - uses: actions/upload-artifact@v4
        with:
          name: hachimi-dll
          path: Hachimi-Edge/target/release/hachimi.dll

  build_cellar:
    name: Build Cellar DLL
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: Hachimi-Hachimi/Cellar
          path: Cellar
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: ./Cellar
      - uses: dtolnay/rust-toolchain@stable
      - name: Build Cellar DLL
        run: cargo build --release
        working-directory: ./Cellar
      - uses: actions/upload-artifact@v4
        with:
          name: cellar-dll
          path: Cellar/target/release/cellar.dll

  build_and_release_installer:
    name: Build and Release Installer
    runs-on: windows-latest
    permissions:
      contents: write
    needs: [build_hachimi_edge, build_cellar]
    env:
      CARGO_TERM_COLOR: always
      ARTIFACT_NAME: hachimi_installer.exe
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@stable

      - name: Download Hachimi DLL
        uses: actions/download-artifact@v4
        with:
          name: hachimi-dll
      - name: Download Cellar DLL
        uses: actions/download-artifact@v4
        with:
          name: cellar-dll

      - name: Build Installer executable
        run: cargo build --release --features compress_dll
        env:
          INSTALLER_REPO_URL: https://github.com/${{ github.repository }}

      - name: Upload Artifact for inspection
        uses: actions/upload-artifact@v4
        with:
          name: installer-windows
          path: target/release/${{ env.ARTIFACT_NAME }}

      - name: Update and push the 'nightly' tag
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -fa nightly -m "Nightly Build from commit ${{ github.sha }}"
          git push origin nightly --force
        shell: bash

      - name: Upload Asset to Nightly Release
        if: github.ref == 'refs/heads/main'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/${{ env.ARTIFACT_NAME }}
          tag: nightly
          overwrite: true
          body: "Latest nightly build from commit `${{ github.sha }}`"